trigger:
- main

variables:
- group: sql-server-container

jobs:
- job: build_test
  displayName: 'Build & Test Container'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: Bash@3
    displayName: 'Build container'
    inputs:
      targetType: 'inline'
      script: |
        docker-compose up -d

  - task: Bash@3
    displayName: 'Wait until container is healthy'
    inputs:
      targetType: 'inline'
      script: |
        wget https://raw.githubusercontent.com/jordyv/wait-for-healthy-container/master/wait-for-healthy-container.sh

        bash wait-for-healthy-container.sh sql-server
    
  - task: Bash@3
    displayName: 'Test container health'
    inputs:
      targetType: 'inline'
      script: |
        sqlcmd -S $(server) -U $(username) -P $(password) -Q "SELECT 1"

  # - task: Bash@3
  #   displayName: 'Test container health'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       max_retries=5
  #       i=1

  #       while [ $i -le $max_retries ]
  #       do
  #         echo "Trying to connect to sql-server container $i ..."

  #         sqlcmd -S $(server) -U $(username) -P $(password) -Q "SELECT 1" && i=0 || i=$(( $i + 1 ))

  #         if [ $i -eq 0 ]
  #         then
  #           echo "sql-server container is working fine"
  #           exit 0
  #         fi

  #         sleep 15s
  #       done

  #       echo "sql-server container is not working"
  #       exit 1