trigger:
- main

jobs:
- job: build_test
  displayName: 'Build & Test Container'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: Bash@3
    displayName: 'Build container'
    inputs:
      targetType: 'inline'
      script: |
        docker-compose up -d

  - task: Bash@3
    displayName: 'Test container health'
    inputs:
      targetType: 'inline'
      script: |
        db_server=127.0.0.1,1433
        db_username=sa
        db_password=sa@@2020

        max_retries=5
        i=1

        while [ $i -le $max_retries ]
        do
          sqlcmd -S $db_server -U $db_username -P $db_password -Q "SELECT 1" && i=0 || i=$(( $i + 1 ))

          if [ $i -eq 0 ]
          then
            exit 0
          fi
        done

        exit 1