services:
    gotenberg:
        image: gotenberg/gotenberg:7
        container_name: gotenberg
        ports:
            - 3000:3000          
        healthcheck:
            test: ["CMD", "curl",  "--fail", "http://localhost:3000/health"]
