trigger:
  branches:
    include:
    - main
  paths:
    include:
    - oracle-db

variables:
- group: oracle-db-container

jobs:
- job: build_test
  displayName: 'Build & Test Container'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: Bash@3
    displayName: 'Build container'
    inputs:
      targetType: 'inline'
      script: |
        docker-compose -f oracle-db/docker-compose.yml up -d

  - task: Bash@3
    displayName: 'Wait until container is healthy'
    inputs:
      targetType: 'inline'
      script: |
        wget https://raw.githubusercontent.com/raschmitt/wait-for-healthy-container/master/wait-for-healthy-container.sh

        bash wait-for-healthy-container.sh oracle-db
    
  - task: Bash@3
    displayName: 'Test container health'
    inputs:
      targetType: 'inline'
      script: |
        $ export SYSTEM_USERNAME=$(SYSTEM_USERNAME)
        $ export SYSTEM_PASSWORD=$(SYSTEM_PASSWORD)

        bash oracle-db/healthcheck.sh

  # - task: Bash@3
  #   displayName: 'Test container health'
  #   inputs:
  #     filePath: 'oracle-db/healthcheck.sh'
