trigger:
  branches:
    include:
    - main
  paths:
    include:
    - rabbitmq

variables:
- group: sql-server-container

jobs:
- job: build_test
  displayName: 'Build & Test Container'
  pool:
    vmImage: 'ubuntu-latest'
  steps:

  - task: Bash@3
    displayName: 'Build container'
    inputs:
      targetType: 'inline'
      script: |
        docker-compose -f sql-server/docker-compose.yml up -d

  - task: Bash@3
    displayName: 'Wait until container is healthy'
    inputs:
      targetType: 'inline'
      script: |
        wget https://raw.githubusercontent.com/raschmitt/wait-for-healthy-container/master/wait-for-healthy-container.sh

        bash wait-for-healthy-container.sh sql-server
    
  - task: Bash@3
    displayName: 'Test container health'
    inputs:
      targetType: 'inline'
      script: |
        sqlcmd -S $(server) -U $(username) -P $(password) -Q "SELECT 1"
