name: Test Container - MongoDB

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'mongo/**'
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'mongo/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
    
      - name: 'Build container'
        run: |
          docker-compose -f mongo/docker-compose.yml up -d
          
      - name: 'Wait until container is healthy'
        run: |
          wget https://raw.githubusercontent.com/raschmitt/wait-for-healthy-container/master/wait-for-healthy-container.sh

          bash wait-for-healthy-container.sh mongo

      - name: 'Test container health'
        run: |
          echo 'db.runCommand("pingg")' | mongosh --quiet | grep -q 'ok: 1' && echo "Healthy" || echo "Unhealthy"; exit 1
