name: Test Container - OracleDb

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'oracle-db/**'
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'oracle-db/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v3
    
      - name: 'Build container'
        run: |
          docker-compose -f oracle-db/docker-compose.yml up -d
          
      - name: 'Checkout repository'
        uses: raschmitt/wait-for-healthy-container/@v1
        with:
          container-name: oracle-db
          
