name: Test Container - OracleDb

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'oracle-db/**'
  pull_request:
    branches: 
      - 'main'
    paths: 
      - 'oracle-db/**'

jobs:
    call-workflow-passing-data:
      uses: raschmitt/dev-containers/.github/workflows/reusable-workflow.yml@feature/add-actions-oracle-db
      with:
        container-name: oracle-db
